% Calculate the loss function without the non-differentiable part
function f_x = J_cost(W, beta, X, Y, ...
                      lambda0, lambda1, lambda2, lambda3, lambda5)

    f_x = lambda0*sum((W.*W).*(log(1+exp(X*beta))-Y.*(X*beta)))...
         +lambda1*sum(balance_cost(W,X))...
         +lambda2*((W.*W)'*(W.*W))...
         +lambda3*sum(beta.^2)...         
         +lambda5*(sum(W.*W)-1)^2;
end